apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ic-webapp
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: BDD_Odoo
        ports:
        - containerPort: 5432
